<a href="https://colab.research.google.com/github/5sadia/Hunar-Intern/blob/task1/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Step 1: Ask user for matrix size
n = int(input("Enter the order of the square matrix (e.g., 3 for 3x3): "))

# Step 2: Collect matrix values
print(f"Enter {n * n} elements (row-wise, separated by space):")
elements = list(map(int, input().split()))

# Step 3: Reshape into square matrix
matrix = np.array(elements).reshape(n, n)

# Step 4: Display the matrix
print("\nInput Matrix:")
print(matrix)

# Step 5: Calculate diagonal sum using loop
diagonal_sum = 0
for i in range(n):
    diagonal_sum += matrix[i][i]

# Step 6: Output the result
print("\nSum of diagonal elements:", diagonal_sum)


Enter the order of the square matrix (e.g., 3 for 3x3): 3
Enter 9 elements (row-wise, separated by space):
7 8 9 6 5 4 3 2 1

Input Matrix:
[[7 8 9]
 [6 5 4]
 [3 2 1]]

Sum of diagonal elements: 13
